language: rust

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry/{src,index}

matrix:
  include:
    - rust: stable
      env: RUST_VERSION=stable COMMAND=bench

    - rust: stable
      env: RUST_VERSION=stable COMMAND=test COV=yes

    - rust: beta
      env: RUST_VERSION=beta COMMAND=test

    - rust: nightly
      env: RUST_VERSION=nightly COMMAND=test

script:
  - ./run-travis-job.sh
